// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqxkfbbrdubfdgaxawdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxeGtmYmJyZHViZmRnYXhhd2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NTc1NzIsImV4cCI6MjA1ODAzMzU3Mn0.1Wnoyl_58TyjUzZaNUT33Wq2uNsH3UTak79RflVj4nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);